version: "3"

services:
  app:
    build: .
    container_name: django
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
      /bin/bash -c "
      /wait-for-it.sh db:5432 -- 
      python manage.py migrate &&
      python manage.py createsuperuser --noinput --username admin --email admin@example.com &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata: