# Generated by Django 5.2.5 on 2025-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_favoritebook_id_favoritebook_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
