# Generated by Django 5.2.5 on 2025-08-24 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrent',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookrent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
