# Generated by Django 5.2.5 on 2025-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_bookrent_id_alter_bookrent_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrent',
            name='status',
        ),
    ]
