# Generated by Django 5.2.5 on 2025-08-25 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_ratings_bookrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='id',
        ),
        migrations.AddField(
            model_name='bookrating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
